spring:
    datasource:
        password: M&24GJ8.}ray
        url: jdbc:mysql://192.168.7.182/stationery_shop?useSSL=false&allowPublicKeyRetrieval=true
        username: sshop
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: none
        sql-format: true
        show-sql: true
    data:
        web:
            pageable:
                one-indexed-parameters: true
    thymeleaf:
        cache: false

server:
    error:
        path: /error



storage:
    root: 'D:\Workspace\JavaScript\ReactJs\stationery-shop\storage'