spring:
    datasource:
        password: mysql
        url: jdbc:mysql://localhost:3306/stationery_shop?useSSL=false&allowPublicKeyRetrieval=true
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: none
        sql-format: true
        show-sql: true


storage:
    root: 'D:\Workspace\JavaScript\ReactJs\stationery-shop\storage'